name: Scrape Territorial.io Results

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape_and_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Load existing data
        id: load_data
        run: |
          if [ -f clan_results.json ]; then
            echo "Loading existing data..."
          else
            echo "[]" > clan_results.json
          fi
      
      - name: Run the scraper script
        run: python main.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add clan_results.json
          git commit -m 'Update clan results data'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
